export { default as Home } from './Home';
export { default as Contact } from './Contact';
export { default as Products } from './Products';
export { default as ProductDetail } from './ProductDetail';
export { default as About } from './About';
export { default as Blog } from './Blog';
export { default as PostDetail } from './PostDetail';
export { default as Auth } from './Auth';
export { default as Settings } from './Settings';
